### ISSUE TITLE
Error using password protected redis as database

### ISSUE THREAD

**Issue by gitSerraNando** [ether/ueberDB#110]
have successfully used redis as database for my etherpad-lite installation, but after adding requirepass to redis.conf, I can't get etherpad-lite to run.

"dbType" : "redis",
   "dbSettings" : {
                    "host"        : "localhost",
                    "port"        : 6379, // Adjust port if you have multiple instances of redis.
                    "database"    : 1, // You should choose a database id that is not already used. If you run redis only for etherpad you can leave this as 0.
                    "password"    : "MyPasswordHere"
                  },

C:\Users\Usuario1\Desktop\Pruebas\Metadockit\etherpad-lite>node node_modules\ep_etherpad-lite\node\server.js
C:\Users\Usuario1\Desktop\Pruebas\Metadockit\etherpad-lite\node_modules\ep_etherpad-lite\node_modules\redis\lib\utils.js:89
        callback(err, res);
        ^

TypeError: callback is not a function
    at Object.callbackOrEmit [as callback_or_emit] (C:\Users\Usuario1\Desktop\Pruebas\Metadockit\etherpad-lite\node_modules\ep_etherpad-lite\node_modules\redis\lib\utils.js:89:9)    at Command.callback (C:\Users\Usuario1\Desktop\Pruebas\Metadockit\etherpad-lite\node_modules\ep_etherpad-lite\node_modules\redis\lib\individualCommands.js:41:15)
    at normal_reply (C:\Users\Usuario1\Desktop\Pruebas\Metadockit\etherpad-lite\node_modules\ep_etherpad-lite\node_modules\redis\index.js:726:21)    at RedisClient.return_reply (C:\Users\Usuario1\Desktop\Pruebas\Metadockit\etherpad-lite\node_modules\ep_etherpad-lite\node_modules\redis\index.js:824:9)
    at JavascriptRedisParser.returnReply (C:\Users\Usuario1\Desktop\Pruebas\Metadockit\etherpad-lite\node_modules\ep_etherpad-lite\node_modules\redis\index.js:192:18)    at JavascriptRedisParser.execute (C:\Users\Usuario1\Desktop\Pruebas\Metadockit\etherpad-lite\node_modules\ep_etherpad-lite\node_modules\redis-parser\lib\parser.js:574:12)
    at Socket.<anonymous> (C:\Users\Usuario1\Desktop\Pruebas\Metadockit\etherpad-lite\node_modules\ep_etherpad-lite\node_modules\redis\index.js:274:27)    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)    at addChunk (_stream_readable.js:263:12)

**Comment by pedrobmarin** [comment]
I noticed you are using with Etherpad. I had a similar problem and this is what I did to make it work:
```
"dbSettings" : {
                   "host"    : "localhost",
                   "port"    : 6379,
                   "client_options": {
                     "password": "PASSWORD"
                   }
                 },
```
