### ISSUE TITLE
Uncaught error in Postgres

### ISSUE THREAD

**Issue by sylvinus** [ether/ueberDB#139]
I'm getting this error after the setup of https://github.com/citizenos/etherpad-lite-heroku :
```
2020-11-18T18:40:35.681161+00:00 app[web.1]: /app/etherpad-lite/src/node_modules/ueberdb2/databases/postgres_common.js:80
2020-11-18T18:40:35.681161+00:00 app[web.1]: if (result.rows.length == 0) {
2020-11-18T18:40:35.681162+00:00 app[web.1]: ^
2020-11-18T18:40:35.681162+00:00 app[web.1]:
2020-11-18T18:40:35.681163+00:00 app[web.1]: TypeError: Cannot read property 'rows' of undefined
2020-11-18T18:40:35.681163+00:00 app[web.1]: at Query.callback (/app/etherpad-lite/src/node_modules/ueberdb2/databases/postgres_common.js:80:16)
2020-11-18T18:40:35.681164+00:00 app[web.1]: at Query.handleError (/app/etherpad-lite/src/node_modules/pg/lib/query.js:139:19)
2020-11-18T18:40:35.681164+00:00 app[web.1]: at process.nextTick (/app/etherpad-lite/src/node_modules/pg/lib/client.js:66:15)
2020-11-18T18:40:35.681164+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:61:11)
```

It seems on line 80 the `err` should be tested on.

thanks!

**Comment by JohnMcLear** [comment]
Try without heroku.

**Comment by JohnMcLear** [comment]
Etherpad has nothing to do with heroku or the repo you are referring to btw.

**Comment by JohnMcLear** [comment]
Try this branch please: https://github.com/ether/ueberDB/pull/143 -- It should hopefully be fixed now.

**Comment by rhansen** [comment]
PR #143 won't fix this issue. I created a separate PR (#144) that should.
