### ISSUE TITLE
"Callback was already called" with Redis

### ISSUE THREAD

**Issue by sylvinus** [ether/ueberDB#140]
At startup with https://github.com/citizenos/etherpad-lite-heroku I'm getting this with a redis db:

```
2020-11-18T19:12:18.530114+00:00 app[web.1]: /app/etherpad-lite/src/node_modules/async/dist/async.js:318
2020-11-18T19:12:18.530126+00:00 app[web.1]: if (fn === null) throw new Error("Callback was already called.");
2020-11-18T19:12:18.530127+00:00 app[web.1]: ^
2020-11-18T19:12:18.530127+00:00 app[web.1]:
2020-11-18T19:12:18.530128+00:00 app[web.1]: Error: Callback was already called.
2020-11-18T19:12:18.530128+00:00 app[web.1]: at /app/etherpad-lite/src/node_modules/async/dist/async.js:318:36
2020-11-18T19:12:18.530129+00:00 app[web.1]: at Object.callbackOrEmit [as callback_or_emit] (/app/etherpad-lite/src/node_modules/redis/lib/utils.js:89:9)
2020-11-18T19:12:18.530129+00:00 app[web.1]: at Command.callback (/app/etherpad-lite/src/node_modules/redis/lib/individualCommands.js:199:15)
2020-11-18T19:12:18.530130+00:00 app[web.1]: at normal_reply (/app/etherpad-lite/src/node_modules/redis/index.js:654:21)
2020-11-18T19:12:18.530130+00:00 app[web.1]: at RedisClient.return_reply (/app/etherpad-lite/src/node_modules/redis/index.js:752:9)
2020-11-18T19:12:18.530130+00:00 app[web.1]: at JavascriptRedisParser.returnReply (/app/etherpad-lite/src/node_modules/redis/index.js:137:18)
2020-11-18T19:12:18.530131+00:00 app[web.1]: at JavascriptRedisParser.execute (/app/etherpad-lite/src/node_modules/redis-parser/lib/parser.js:544:14)
2020-11-18T19:12:18.530131+00:00 app[web.1]: at Socket.<anonymous> (/app/etherpad-lite/src/node_modules/redis/index.js:218:27)
2020-11-18T19:12:18.530132+00:00 app[web.1]: at Socket.emit (events.js:182:13)
2020-11-18T19:12:18.530132+00:00 app[web.1]: at Socket.EventEmitter.emit (domain.js:442:20)
```

thanks!

**Comment by JohnMcLear** [comment]
I don't think this is an ether problem.

**Comment by JohnMcLear** [comment]
Can you please try using ether/etherpad-lite

If that works then it's probable that your problem is something to do with the citizenos repo

**Comment by JohnMcLear** [comment]
Tested Redis, it's all good and all tests are passing.
