### ISSUE TITLE
sqlite install error

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ueberDB#150]
Afaik this is why we dropped sqlite3

```
yp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/etherpad-lite/src/                                                             node_modules/ueberdb2/node_modules/sqlite3/.node-gyp'
gyp ERR! System Linux 3.10.0-1160.6.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gy                                                             p/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/etherpad-li                                                             te/src/node_modules/ueberdb2/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/                                                             node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/etherpad-li                                                             te/src/node_modules/ueberdb2/node_modules/sqlite3/lib/binding/napi-v3-linux-x64"                                                              "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi                                                             _label=napi-v3"
gyp ERR! cwd /home/etherpad-lite/src/node_modules/ueberdb2/node_modules/sqlite3
gyp ERR! node -v v13.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_mo                                                             dules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --                                                             module=/home/etherpad-lite/src/node_modules/ueberdb2/node_modules/sqlite3/lib/bi                                                             nding/napi-v3-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_pa                                                             th=/home/etherpad-lite/src/node_modules/ueberdb2/node_modules/sqlite3/lib/bindin                                                             g/napi-v3-linux-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=3                                                              --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/etherpad-lite/src                                                             /node_modules/ueberdb2/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi                                                             ld_process.js:286:5)
node-pre-gyp ERR! System Linux 3.10.0-1160.6.1.el7.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/home/etherpad-lite/src/node_modules/                                                             ueberdb2/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/etherpad-lite/src/node_modules/ueberdb2/node_modules                                                             /sqlite3
node-pre-gyp ERR! node -v v13.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp                                                             /bin/node-gyp.js configure --fallback-to-build --module=/home/etherpad-lite/src/                                                             node_modules/ueberdb2/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sq                                                             lite3.node --module_name=node_sqlite3 --module_path=/home/etherpad-lite/src/node                                                             _modules/ueberdb2/node_modules/sqlite3/lib/binding/napi-v3-linux-x64 --napi_vers                                                             ion=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
```

**Comment by rhansen** [comment]
I'm going to close this—the sqlite package has changed a fair amount since this was reported.
