### ISSUE TITLE
CouchDB tests fail

### ISSUE THREAD

**Issue by rhansen** [ether/ueberDB#159]
When CouchDB is uncommented in `test/lib/databases.js` some of the tests fail with the following error (line numbers are probably incorrect):

```
     Uncaught Error: Error: Document update conflict.
      at handleError (databases/couch_db.js:25:17)
      at /home/runner/work/ueberDB/ueberDB/databases/couch_db.js:128:7
      at Request._callback (node_modules/nano/lib/nano.js:174:9)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.EventEmitter.emit (domain.js:483:12)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at Request.EventEmitter.emit (domain.js:483:12)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at IncomingMessage.EventEmitter.emit (domain.js:483:12)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by rhansen** [comment]
Fixed by #236.
