### ISSUE TITLE
MongoError: $not cannot have a regex with etherpad 1.8.8 & mongodb 3.2.11

### ISSUE THREAD

**Issue by brunob** [ether/ueberDB#192]
Hi, since version 1.8.8 of etherpad we can't use mongodb. First i got an error pointing that : 

```[2021-03-03 20:17:57.345] [ERROR] server - Error: You must specify a mongodb database
    at new exports.Database (/opt/etherpad/master/src/node_modules/ueberdb2/databases/mongodb_db.js:22:36)
    at exports.Database.init (/opt/etherpad/master/src/node_modules/ueberdb2/index.js:66:14)
    at Promise (/opt/etherpad/master/src/node/db/DB.js:43:6)
    at new Promise (<anonymous>)
    at Object.exports.init (/opt/etherpad/master/src/node/db/DB.js:42:34)
    at Object.exports.start (/opt/etherpad/master/src/node/server.js:139:14)
    at Object.<anonymous> (/opt/etherpad/master/src/node/server.js:266:38)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
[2021-03-03 20:17:57.345] [INFO] server - Exiting...
```

So i've updated our settings.json to add `"url": "mongodb://localhost:27017",` in `dbSettings` field, and now i get :

```
[2021-03-03 20:20:58.641] [INFO] console - Your Etherpad version is 1.8.11 (ad84c8a)
[2021-03-03 20:21:00.018] [ERROR] server - MongoError: $not cannot have a regex
    at Connection.<anonymous> (/opt/etherpad/master/src/node_modules/mongodb/lib/core/connection/pool.js:451:61)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at processMessage (/opt/etherpad/master/src/node_modules/mongodb/lib/core/connection/connection.js:451:10)
    at Socket.<anonymous> (/opt/etherpad/master/src/node_modules/mongodb/lib/core/connection/connection.js:620:15)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
[2021-03-03 20:21:00.021] [INFO] server - Exiting...
```
Mongo version is : 

```
apt policy mongodb
mongodb:
  Installé : 1:3.2.11-2+deb9u2
  Candidat : 1:3.2.11-2+deb9u2
 Table de version :
 *** 1:3.2.11-2+deb9u2 990
        990 http://security.debian.org stretch/updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1:3.2.11-2+deb9u1 990
        990 http://ftp.fr.debian.org/debian stretch/main amd64 Packages
```

And i've tested with npm package mongodb on v2.2.28 and @latest which is mongodb@3.6.4.

Should we forget to use mongodb with etherpad or are we missing something ?

**Comment by JohnMcLear** [comment]
https://github.com/ether/ueberDB/actions/runs/607156179/workflow#L21

We test mongo in CI

https://github.com/ether/ueberDB/blob/master/test/lib/databases.js#L41

Is the config.

**Comment by brunob** [comment]
Sorry @JohnMcLear but i don't get your comment, should we forget using mongo with etherpad and migrate all ours pads to mysql or postgre ? Or should i ping @Sylchauf about this ?

**Comment by JohnMcLear** [comment]
We have test coverage showing mongo should be fine.  If you copy the test config format it should be working.

**Comment by brunob** [comment]
Ha, misunderstanding here :) I was not pointing the config change to connect to mongo, as i've said, i get it, but this error : `MongoError: $not cannot have a regex`.

**Comment by JohnMcLear** [comment]
@brunob I'm confused...  Our tests show that mongo **is working**.  Can you quickly try to bring up a clean instance on a VM and try an install?  My assumption atm (and I know nothing about mongo) is that your mongodb has issues but I can't debug what without knowing if it's an issue with config/database/UeberDB.  We have CI to try to rule out UeberDB but that doesn't mean it's not a fault within UeberDB!

**Comment by Sylchauf** [comment]
@brunob Mongodb is too old. $not accept regex since MongoDB 4.0.7

We probably must specify the required version in th readme

**Comment by JohnMcLear** [comment]
https://github.com/ether/ueberDB/blob/master/package.json#L28 is what we target 3.6...  So breaking change in Mongo API?  No deprecation notices?  I guess the mongo client is broken then 4+?

**Comment by Sylchauf** [comment]
The NodeJS MongoDB Driver on [NPMjs](https://www.npmjs.com/package/mongodb) (latest version 3.6.4) is not the same thing as [MongoDB Database Server](https://www.mongodb.com/try/download/community) (latest version 4.4.4) 

The first is needed (on NodeJS environment) to communicate with the second ! 

@brunob must upgrade his MongoDB Database Server to the version 4.0.7 at least. This is needed because regex is used in the `$not` operator in the `findKeys` method ([see here](https://github.com/ether/ueberDB/blob/19d187f3a5c5e76ee6ddaf58976c6dab78b03906/databases/mongodb_db.js#L75))

We could do a refactor to not use regex, but IMY, the requirement of MongoDB Server 4.0.7 is not a bad idea. Furthermore, this syntax is more performant than the workaround required to remove the regex in the $not operator

**Comment by JohnMcLear** [comment]
Great.  Ye we should update readme to specify mongo dB version required.  Can you send a PR for that plz?  Thanks for explanation too!

**Comment by brunob** [comment]
> @brunob Your Mongodb instance is too old. $not accept regex since MongoDB 4.0.7

'k, we should try to get mongo 4.x on debian 9 (which default proposed version is 3.x) or update our VMs.

**Comment by brunob** [comment]
FTR, we have moved to mongodb 4.4.4 + a switch to a cluster mode with replicaset and imported a dump of our pads in the cluster. After that we get problems with pads IDs, so i wonder if we would simply dump all pads using etherpad API and inject them in the new cluster (just have to find a script fort that).

**Comment by brunob** [comment]
I've found toe origin of the bug for pads IDs, i'll put this in a specific ticket and closing this one.

FTR, etherpad users switching from mongo 3 to 4 should update their settings from something like this :

```
"dbSettings" : {
    "host": "127.0.0.1",
    "port": 27017,
    "dbname" : "dbpad01"
  },
```

to

```
  "dbSettings" : {
    "url": "mongodb://127.0.0.1",
    "dbName" : "dbpad01",
    "collection": "store"
  },
```

Note the url style config instead of host + port, and the `collection` config which should be set to `store` in order to avoid the `ueberdb` default ref https://github.com/ether/ueberDB/blob/master/databases/mongodb_db.js#L24
